# base image
FROM node:latest

# set working directory
RUN mkdir -p /srv/app/server
WORKDIR /srv/app/server

COPY package*.json /srv/app/server/
RUN npm install 
COPY . /srv/app/server/
# add `/app/node_modules/.bin` to $PATH
#ENV PATH /app/node_modules/.bin:$PATH

#RUN npm install react-scripts@3.0.1 -g 
# start app
EXPOSE 5000
CMD ["npm", "run", "dev"]